/* Generated By:JJTree: Do not edit this line. ASTAddExpress.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAddExpress extends SimpleNode {
  public ASTAddExpress(int id) {
    super(id);
  }

  public ASTAddExpress(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a36d112ecc4f0c0b328c798c7ba7897a (do not edit this line) */
