/* Generated By:JJTree: Do not edit this line. ASTBoolExpress.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBoolExpress extends SimpleNode {
  public ASTBoolExpress(int id) {
    super(id);
  }

  public ASTBoolExpress(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bfa25a217c324d74551dabf9a3238d0e (do not edit this line) */
