/* Generated By:JJTree: Do not edit this line. ASTBoolCompOper.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBoolCompOper extends SimpleNode {
  public ASTBoolCompOper(int id) {
    super(id);
  }

  public ASTBoolCompOper(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ea6333c4ee70449875ab2f0fdb5e3700 (do not edit this line) */
