/* Generated By:JJTree: Do not edit this line. ASTBoolExpressAnd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBoolExpressAnd extends SimpleNode {
  public ASTBoolExpressAnd(int id) {
    super(id);
  }

  public ASTBoolExpressAnd(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b2cfdfd6ae737f1bdaf933f66b099b7e (do not edit this line) */
