/* Generated By:JJTree: Do not edit this line. ASTBoolExpressComp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBoolExpressComp extends SimpleNode {
  public ASTBoolExpressComp(int id) {
    super(id);
  }

  public ASTBoolExpressComp(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8fe67b506516a55555755fb03a714bf9 (do not edit this line) */
