/* Generated By:JJTree: Do not edit this line. ASTCheckSyntax.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCheckSyntax extends SimpleNode {
  public ASTCheckSyntax(int id) {
    super(id);
  }

  public ASTCheckSyntax(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b62eb1685aa923bf594d4d2fd97a5876 (do not edit this line) */
