/* Generated By:JJTree: Do not edit this line. ASTConstExpress.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConstExpress extends SimpleNode {
  public ASTConstExpress(int id) {
    super(id);
  }

  public ASTConstExpress(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fdc615bf1c6ad9aa2422c7139e591083 (do not edit this line) */
