/* Generated By:JJTree: Do not edit this line. ASTFuncCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFuncCall extends SimpleNode {
  public ASTFuncCall(int id) {
    super(id);
  }

  public ASTFuncCall(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cb3276b9cf2949f19f9bad8d30be67d5 (do not edit this line) */
