/* Generated By:JJTree: Do not edit this line. ASTIfStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfStmt extends SimpleNode {
  public ASTIfStmt(int id) {
    super(id);
  }

  public ASTIfStmt(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=80a1bc739c85eb3bf81ee28c43f11824 (do not edit this line) */
