/* Generated By:JJTree: Do not edit this line. ASTReturnStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReturnStmt extends SimpleNode {
  public ASTReturnStmt(int id) {
    super(id);
  }

  public ASTReturnStmt(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0cadb79d79c60bf899078a998f32ef1c (do not edit this line) */
