/* Generated By:JJTree: Do not edit this line. ASTStmtBlock.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStmtBlock extends SimpleNode {
  public ASTStmtBlock(int id) {
    super(id);
  }

  public ASTStmtBlock(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=49c35ebaffdf42429a8ee416519e1f87 (do not edit this line) */
