/* Generated By:JJTree: Do not edit this line. ASTUnaExpress.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUnaExpress extends SimpleNode {
  public ASTUnaExpress(int id) {
    super(id);
  }

  public ASTUnaExpress(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=52ec83615e85cd3785ea1ec2e780fa03 (do not edit this line) */
