/* Generated By:JJTree: Do not edit this line. ASTVarAsgn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarAsgn extends SimpleNode {
  public ASTVarAsgn(int id) {
    super(id);
  }

  public ASTVarAsgn(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ee172b6044f348dfa8f4d1008e778d95 (do not edit this line) */
