/* Generated By:JavaCC: Do not edit this line. CLangTreeConstants.java Version 7.0.5 */
public interface CLangTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCHECKSYNTAX = 1;
  public int JJTALLPARAMETERS = 2;
  public int JJTPARAMETER = 3;
  public int JJTFUNC = 4;
  public int JJTVARDEF = 5;
  public int JJTVARASGN = 6;
  public int JJTVARINITASGN = 7;
  public int JJTIFSTMT = 8;
  public int JJTWHILESTMT = 9;
  public int JJTFORSTMT = 10;
  public int JJTRETURNSTMT = 11;
  public int JJTSTMT = 12;
  public int JJTSTMTBLOCK = 13;
  public int JJTFUNCCALL = 14;
  public int JJTEXPRESS = 15;
  public int JJTASSIGNEXPRESS = 16;
  public int JJTBOOLEXPRESS = 17;
  public int JJTBOOLEXPRESSOR = 18;
  public int JJTBOOLEXPRESSAND = 19;
  public int JJTBOOLEXPRESSEQ = 20;
  public int JJTBOOLCOMPOPER = 21;
  public int JJTBOOLEXPRESSCOMP = 22;
  public int JJTADDEXPRESS = 23;
  public int JJTMULTEXPRESS = 24;
  public int JJTUNAEXPRESS = 25;
  public int JJTCONSTEXPRESS = 26;


  public String[] jjtNodeName = {
    "Start",
    "CheckSyntax",
    "AllParameters",
    "Parameter",
    "Func",
    "VarDef",
    "VarAsgn",
    "VarInitAsgn",
    "IfStmt",
    "WhileStmt",
    "ForStmt",
    "ReturnStmt",
    "Stmt",
    "StmtBlock",
    "FuncCall",
    "Express",
    "AssignExpress",
    "BoolExpress",
    "BoolExpressOr",
    "BoolExpressAnd",
    "BoolExpressEq",
    "BoolCompOper",
    "BoolExpressComp",
    "AddExpress",
    "MultExpress",
    "UnaExpress",
    "ConstExpress",
  };
}
/* JavaCC - OriginalChecksum=d19feebc1a99a18862b3eeac4c57ad99 (do not edit this line) */
