/* Generated By:JavaCC: Do not edit this line. CLangDefaultVisitor.java Version 7.0.5 */
public class CLangDefaultVisitor implements CLangVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCheckSyntax node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAllParameters node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParameter node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunc node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarDef node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarAsgn node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarInitAsgn node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTForStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTReturnStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStmtBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFuncCall node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpress node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssignExpress node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoolExpress node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoolExpressOr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoolExpressAnd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoolExpressEq node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoolCompOper node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoolExpressComp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAddExpress node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMultExpress node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUnaExpress node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTConstExpress node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=5fb9b269cdddc43e58fd1aa611a4b1fb (do not edit this line) */
